[build]
  functions = "functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/"
  to   = "/indexbt.html"
  status = 200

[[redirects]]
  from = "/topline"
  to   = "/toplinebt.html"
  status = 200

[[redirects]]
  from = "/underperformers"
  to   = "/underperformersbt.html"
  status = 200
